#!/usr/bin/env python3

"""
Spotify Music Analyzer
Validate MusicBrainz recording + artist genre coverage.

Purpose
-------
Validate the result of the previous MusicBrainz artist genre test
using only the local SQLite database and the JSON generated by:

    tools/test_musicbrainz_artist_genres.py

This script does NOT:
- access the MusicBrainz API;
- modify SQLite;
- create or modify database tables.

It verifies:

1. Which MusicBrainz artists have no genres.
2. Which recordings are associated with those artists.
3. Every linked MusicBrainz recording and its artists.
4. Recording-level genres already stored locally.
5. Artist genres obtained during the previous test.
6. Whether any recording has neither recording genres nor
   genres available from any associated artist.

The final condition is the key validation for the proposed
MusicBrainz genre strategy.
"""

import json
import sqlite3
from collections import defaultdict
from pathlib import Path


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

DATABASE = (
    BASE_DIR
    / "data"
    / "spotify_music.db"
)

TEST_JSON = (
    BASE_DIR
    / "data"
    / "musicbrainz_artist_genres_test.json"
)


# ============================================================
# DATABASE
# ============================================================

def get_connection():
    """
    Open SQLite in read-only/query-only mode.
    """

    connection = sqlite3.connect(
        DATABASE
    )

    connection.row_factory = sqlite3.Row

    connection.execute(
        "PRAGMA query_only = ON"
    )

    return connection


def load_recordings(connection):
    """
    Load Spotify -> MusicBrainz recording
    relationships.
    """

    rows = connection.execute(
        """
        SELECT DISTINCT
            spotify_id,
            mb_recording_id
        FROM track_musicbrainz
        ORDER BY
            mb_recording_id,
            spotify_id
        """
    ).fetchall()

    result = defaultdict(list)

    for row in rows:

        result[
            row["mb_recording_id"]
        ].append(
            row["spotify_id"]
        )

    return dict(result)


def load_recording_artists(connection):
    """
    Load MusicBrainz recording -> artist
    relationships.
    """

    rows = connection.execute(
        """
        SELECT
            recording_id,
            artist_id,
            position,
            joinphrase,
            credited_name
        FROM mb_recording_artists
        ORDER BY
            recording_id,
            position
        """
    ).fetchall()

    result = defaultdict(list)

    for row in rows:

        result[
            row["recording_id"]
        ].append(
            {
                "artist_id":
                    row["artist_id"],

                "position":
                    row["position"],

                "joinphrase":
                    row["joinphrase"],

                "credited_name":
                    row["credited_name"],
            }
        )

    return dict(result)


def load_recording_genres(connection):
    """
    Load the genres/tags currently normalized
    against MusicBrainz recordings.

    NOTE:
    The existing mb_tags data originates from the
    previous MusicBrainz tag normalization. It is
    displayed as existing recording metadata only.
    """

    rows = connection.execute(
        """
        SELECT DISTINCT
            mrt.recording_id,
            mt.name
        FROM mb_recording_tags AS mrt
        JOIN mb_tags AS mt
          ON mt.id = mrt.tag_id
        ORDER BY
            mrt.recording_id,
            mt.name
        """
    ).fetchall()

    result = defaultdict(list)

    for row in rows:

        result[
            row["recording_id"]
        ].append(
            row["name"]
        )

    return dict(result)


def load_artists(connection):
    """
    Load MusicBrainz artist names.
    """

    rows = connection.execute(
        """
        SELECT
            mb_artist_id,
            name
        FROM mb_artists
        """
    ).fetchall()

    return {
        row["mb_artist_id"]:
            row["name"]
        for row in rows
    }


# ============================================================
# TEST JSON
# ============================================================

def load_artist_genre_test():
    """
    Load the previous API test result.
    """

    if not TEST_JSON.exists():

        raise FileNotFoundError(
            "Previous artist genre test JSON "
            "was not found:\n"
            f"{TEST_JSON}"
        )

    with TEST_JSON.open(
        "r",
        encoding="utf-8",
    ) as file:

        return json.load(file)


def build_artist_genre_index(test_data):
    """
    Build:

        artist_id -> {
            name,
            genres,
            status
        }
    """

    result = {}

    for item in test_data.get(
        "results",
        [],
    ):

        artist_id = item.get(
            "artist_id"
        )

        if not artist_id:
            continue

        genres = []

        for genre in item.get(
            "genres",
            [],
        ):

            name = genre.get(
                "name"
            )

            if name and name not in genres:

                genres.append(name)

        result[artist_id] = {
            "name":
                item.get(
                    "artist_name",
                    "",
                ),

            "genres":
                sorted(
                    genres,
                    key=str.lower,
                ),

            "status":
                item.get(
                    "status"
                ),
        }

    return result


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 78)
    print(
        "SPOTIFY MUSIC ANALYZER — "
        "MUSICBRAINZ GENRE COVERAGE VALIDATION"
    )
    print("=" * 78)

    print()
    print(
        f"Database: {DATABASE}"
    )

    print(
        f"Test JSON: {TEST_JSON}"
    )

    # --------------------------------------------------------
    # Load local data
    # --------------------------------------------------------

    connection = get_connection()

    try:

        spotify_recordings = (
            load_recordings(
                connection
            )
        )

        recording_artists = (
            load_recording_artists(
                connection
            )
        )

        recording_genres = (
            load_recording_genres(
                connection
            )
        )

        artist_names = (
            load_artists(
                connection
            )
        )

    finally:

        connection.close()

    test_data = load_artist_genre_test()

    artist_genres = (
        build_artist_genre_index(
            test_data
        )
    )

    # --------------------------------------------------------
    # Basic counts
    # --------------------------------------------------------

    recordings = set(
        spotify_recordings.keys()
    )

    artists = set(
        artist_genres.keys()
    )

    artists_without_genres = {
        artist_id
        for artist_id in artists
        if not artist_genres[
            artist_id
        ]["genres"]
    }

    artists_with_genres = (
        artists
        - artists_without_genres
    )

    # --------------------------------------------------------
    # Artists without genres
    # --------------------------------------------------------

    print()
    print("=" * 78)
    print(
        "ARTISTS WITHOUT GENRES"
    )
    print("=" * 78)

    print()

    if not artists_without_genres:

        print(
            "All tested artists have at least "
            "one MusicBrainz genre."
        )

    else:

        print(
            f"Artists without genres: "
            f"{len(artists_without_genres)}"
        )

        for artist_id in sorted(
            artists_without_genres
        ):

            name = (
                artist_genres[
                    artist_id
                ].get("name")
                or artist_names.get(
                    artist_id,
                    "UNKNOWN",
                )
            )

            print()
            print(
                f"Artist: {name}"
            )

            print(
                f"MBID:   {artist_id}"
            )

            associated_recordings = []

            for recording_id in recordings:

                relations = (
                    recording_artists.get(
                        recording_id,
                        [],
                    )
                )

                if any(
                    relation[
                        "artist_id"
                    ] == artist_id
                    for relation in relations
                ):

                    associated_recordings.append(
                        recording_id
                    )

            print(
                "Recordings:"
            )

            if associated_recordings:

                for recording_id in (
                    associated_recordings
                ):

                    spotify_ids = (
                        spotify_recordings[
                            recording_id
                        ]
                    )

                    print(
                        f"  {recording_id}"
                    )

                    print(
                        "    Spotify: "
                        + ", ".join(
                            spotify_ids
                        )
                    )

            else:

                print(
                    "  NONE"
                )

    # --------------------------------------------------------
    # Recording-level validation
    # --------------------------------------------------------

    print()
    print("=" * 78)
    print(
        "RECORDING → ARTIST GENRE VALIDATION"
    )
    print("=" * 78)

    recordings_without_any_genre = []

    recordings_with_recording_genres = []
    recordings_with_artist_genres = []
    recordings_with_both = []

    for recording_id in sorted(
        recordings
    ):

        spotify_ids = (
            spotify_recordings[
                recording_id
            ]
        )

        own_genres = (
            recording_genres.get(
                recording_id,
                [],
            )
        )

        relations = (
            recording_artists.get(
                recording_id,
                [],
            )
        )

        artist_genre_map = {}

        for relation in relations:

            artist_id = relation[
                "artist_id"
            ]

            artist_info = artist_genres.get(
                artist_id
            )

            if not artist_info:

                continue

            genres = artist_info[
                "genres"
            ]

            if genres:

                artist_genre_map[
                    artist_id
                ] = genres

        all_artist_genres = sorted(
            {
                genre
                for genres in (
                    artist_genre_map.values()
                )
                for genre in genres
            },
            key=str.lower,
        )

        has_recording_genres = bool(
            own_genres
        )

        has_artist_genres = bool(
            all_artist_genres
        )

        if has_recording_genres:

            recordings_with_recording_genres.append(
                recording_id
            )

        if has_artist_genres:

            recordings_with_artist_genres.append(
                recording_id
            )

        if (
            has_recording_genres
            and has_artist_genres
        ):

            recordings_with_both.append(
                recording_id
            )

        if (
            not has_recording_genres
            and not has_artist_genres
        ):

            recordings_without_any_genre.append(
                recording_id
            )

        print()
        print(
            f"MB Recording: {recording_id}"
        )

        print(
            "Spotify tracks: "
            + ", ".join(
                spotify_ids
            )
        )

        print(
            "Recording metadata: "
            + (
                ", ".join(
                    own_genres
                )
                if own_genres
                else "NONE"
            )
        )

        print(
            "Artists:"
        )

        if not relations:

            print(
                "  NONE"
            )

        else:

            for relation in relations:

                artist_id = relation[
                    "artist_id"
                ]

                artist_info = (
                    artist_genres.get(
                        artist_id,
                        {},
                    )
                )

                artist_name = (
                    artist_info.get(
                        "name"
                    )
                    or artist_names.get(
                        artist_id,
                        "UNKNOWN",
                    )
                )

                genres = (
                    artist_info.get(
                        "genres",
                        [],
                    )
                )

                print(
                    f"  {artist_name}"
                )

                print(
                    f"    MBID: {artist_id}"
                )

                print(
                    "    Genres: "
                    + (
                        ", ".join(
                            genres
                        )
                        if genres
                        else "NONE"
                    )
                )

    # --------------------------------------------------------
    # Final coverage analysis
    # --------------------------------------------------------

    total = len(recordings)

    recording_count = len(
        recordings_with_recording_genres
    )

    artist_count = len(
        recordings_with_artist_genres
    )

    both_count = len(
        recordings_with_both
    )

    uncovered_count = len(
        recordings_without_any_genre
    )

    combined_count = total - uncovered_count

    print()
    print("=" * 78)
    print(
        "FINAL COVERAGE VALIDATION"
    )
    print("=" * 78)

    print()

    print(
        f"Linked recordings:                    "
        f"{total}"
    )

    print(
        f"With recording-level metadata:        "
        f"{recording_count} / {total} "
        f"({recording_count * 100 / total:.2f}%)"
        if total
        else
        "With recording-level metadata:        0 / 0"
    )

    print(
        f"With artist genres:                    "
        f"{artist_count} / {total} "
        f"({artist_count * 100 / total:.2f}%)"
        if total
        else
        "With artist genres:                    0 / 0"
    )

    print(
        f"With both:                             "
        f"{both_count} / {total} "
        f"({both_count * 100 / total:.2f}%)"
        if total
        else
        "With both:                             0 / 0"
    )

    print(
        f"Covered by at least one source:        "
        f"{combined_count} / {total} "
        f"({combined_count * 100 / total:.2f}%)"
        if total
        else
        "Covered by at least one source:        0 / 0"
    )

    print(
        f"Without any genre information:         "
        f"{uncovered_count} / {total} "
        f"({uncovered_count * 100 / total:.2f}%)"
        if total
        else
        "Without any genre information:         0 / 0"
    )

    # --------------------------------------------------------
    # Critical result
    # --------------------------------------------------------

    print()
    print("-" * 78)
    print(
        "CRITICAL VALIDATION RESULT"
    )
    print("-" * 78)

    print()

    if not recordings_without_any_genre:

        print(
            "SUCCESS"
        )

        print()
        print(
            "Every linked MusicBrainz recording has "
            "either recording-level metadata or at "
            "least one associated artist with genres."
        )

        print()
        print(
            "The MusicBrainz recording + artist genre "
            "strategy provides complete genre coverage "
            "for this test dataset."
        )

    else:

        print(
            "INCOMPLETE"
        )

        print()
        print(
            "The following recordings have neither "
            "recording-level metadata nor artist genres:"
        )

        for recording_id in sorted(
            recordings_without_any_genre
        ):

            print(
                f"  {recording_id}"
            )

    # --------------------------------------------------------
    # Artist coverage summary
    # --------------------------------------------------------

    print()
    print("=" * 78)
    print(
        "ARTIST COVERAGE SUMMARY"
    )
    print("=" * 78)

    total_artists = len(
        artists
    )

    print()

    print(
        f"Artists tested:                       "
        f"{total_artists}"
    )

    print(
        f"Artists with genres:                  "
        f"{len(artists_with_genres)} / "
        f"{total_artists} "
        f"({len(artists_with_genres) * 100 / total_artists:.2f}%)"
        if total_artists
        else
        "Artists with genres:                  0 / 0"
    )

    print(
        f"Artists without genres:               "
        f"{len(artists_without_genres)} / "
        f"{total_artists} "
        f"({len(artists_without_genres) * 100 / total_artists:.2f}%)"
        if total_artists
        else
        "Artists without genres:               0 / 0"
    )

    print()
    print("=" * 78)
    print(
        "VALIDATION COMPLETED"
    )
    print("=" * 78)

    print()
    print(
        "SQLite database was NOT modified."
    )

    print(
        "No MusicBrainz API requests were performed."
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )